language: python
python:
- '3.6'
before_install:
- sudo apt-get update
- sudo apt-get install -qq python-numpy python-scipy
install:
- pip install -r requirements.txt
script:
- py.test tests
- cookiecutter . -o temp/ --no-input -v
- cd temp/project_name && python setup.py test && cd -
- cd temp/project_name && python setup.py sdist && cd -
