language: python
python:
- '3.6'
before_install:
- sudo apt-get update
- sudo apt-get install -qq python-numpy python-scipy
install:
# Install conda, to be used from within the generated project
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
# Actually install the requirements to be able to run cookiecutter
- pip install -r requirements.txt
script:
- py.test tests
- cookiecutter . -o temp/ --no-input -v
- cd temp/project_name && python setup.py test && cd -
- cd temp/project_name && python setup.py sdist && cd -
- cd temp/project_name && conda env create -f environment.yml
