name: ds_prod
dependencies:
- flask=0.12.2
- python=3
- numpy=1.13.1
- scikit-learn=0.18.1
- dill=0.2.6
- pandas=0.20.3
- scipy=0.19.1

- pip:
  - git+https://github.com/BigDataRepublic/bdr-engineering-stack.git@develop#subdirectory=data-science-production-container/ds_prod_api
